(function(){
  const notice=document.createElement('div');notice.style.cssText='margin:16px auto;padding:14px 18px;max-width:1100px;border:1px solid #fabe49;border-radius:12px;background:#fff8df;color:#2e2d4d;font-weight:700';notice.textContent='Banco compartilhado: alterações feitas nesta tela permanecem como rascunho neste navegador até serem publicadas em uma nova versão DEV da pasta do projeto.';document.querySelector('main')?.prepend(notice);
  const api=window.MicrosetSiteAdmin, customKey=api.CUSTOM_KEY;
  const readCustom=()=>api.readStructure(), writeCustom=(v)=>localStorage.setItem(customKey,JSON.stringify(v));
  const parent=document.querySelector('#parentSection'), list=document.querySelector('#structureList'), coreList=document.querySelector('#coreList');
  let core=api.readCore();
  const esc=(v)=>{const d=document.createElement('div');d.textContent=v||'';return d.innerHTML;};
  function renderCore(){coreList.innerHTML=core.map((s,i)=>`<div class="core-row" data-core="${s.id}"><span>${i+1}</span><input type="text" value="${esc(s.name)}" maxlength="32"><label><input type="checkbox" ${s.visible!==false?'checked':''}> Visível</label><button type="button" data-up ${i===0?'disabled':''}>↑</button><button type="button" data-down ${i===core.length-1?'disabled':''}>↓</button></div>`).join('');coreList.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(b.closest('.core-row').dataset.core,-1));coreList.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(b.closest('.core-row').dataset.core,1));}
  function move(id,d){const i=core.findIndex(s=>s.id===id),j=i+d;if(j<0||j>=core.length)return;[core[i],core[j]]=[core[j],core[i]];renderCore();}
  function collect(){coreList.querySelectorAll('.core-row').forEach(r=>{const s=core.find(x=>x.id===r.dataset.core);s.name=r.querySelector('input[type=text]').value.trim()||s.name;s.visible=r.querySelector('input[type=checkbox]').checked;});return core;}
  function render(){const custom=readCustom();parent.innerHTML=core.map(s=>`<option value="core:${s.id}">${esc(s.name)}</option>`).join('')+custom.map(s=>`<option value="custom:${s.id}">${esc(s.name)}</option>`).join('');list.innerHTML=core.concat(custom).map(s=>`<div class="structure-item"><div><strong>${esc(s.name)}</strong><small>${(s.subsections||[]).length?esc(s.subsections.map(x=>x.name).join(' • ')):'Sem subseções'}</small></div>${core.some(x=>x.id===s.id)?'':`<button class="remove-btn" data-remove="${s.id}">Excluir</button>`}</div>`).join('');list.querySelectorAll('[data-remove]').forEach(b=>b.onclick=()=>{writeCustom(custom.filter(s=>s.id!==b.dataset.remove));location.reload();});}
  document.querySelector('#saveCoreBtn').onclick=()=>{api.writeCore(collect());location.reload();};
  document.querySelector('#sectionForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#sectionName').value.trim();if(!name)return;const data=readCustom();data.push({id:api.slugify(name)+'-'+Date.now(),name,subsections:[]});writeCustom(data);location.reload();};
  document.querySelector('#subsectionForm').onsubmit=e=>{e.preventDefault();const name=document.querySelector('#subsectionName').value.trim(),[type,id]=parent.value.split(':');if(!name)return;if(type==='core'){core=api.readCore();const s=core.find(x=>x.id===id);s?.subsections.push({id:api.slugify(name)+'-'+Date.now(),name,visible:true});api.writeCore(core);}else{const data=readCustom(),s=data.find(x=>x.id===id);s?.subsections.push({id:api.slugify(name)+'-'+Date.now(),name,visible:true});writeCustom(data);}location.reload();};
  renderCore();render();
})();
